"""
Local Writer for image_text pipeline outputs.

Generates an HTML page showing the generated title, body, and images
to allow users to view the result in a browser.
"""

import json
import os
from datetime import datetime
from html import escape
from pathlib import Path
from typing import List, Dict, Any


def write_local_output(
    title: str,
    body: str,
    image_paths: List[str],
    output_dir: str = "workspace/outputs/image_text",
) -> Dict[str, Any]:
    """
    Write image_text pipeline output to local HTML file and metadata JSON.

    Args:
        title: Generated title
        body: Generated body text
        image_paths: List of local image paths
        output_dir: Base output directory (default: workspace/outputs/image_text)

    Returns:
        Dictionary with success status, output path, and metadata
    """
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    safe_title = "".join(c for c in title if c.isalnum() or c in (" ", "-")).strip()
    if not safe_title:
        safe_title = f"output-{timestamp}"

    path = Path(output_dir)
    path.mkdir(parents=True, exist_ok=True)

    output_subdir = path / safe_title
    output_subdir.mkdir(exist_ok=True)

    # Generate HTML content
    html_content = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{escape(title)}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            max-width: 800px;
            margin: 2rem auto;
            padding: 0 1rem;
            line-height: 1.6;
            color: #333;
        }}
        .header {{
            margin-bottom: 2rem;
        }}
        .title {{
            font-size: 2rem;
            font-weight: 600;
            margin-bottom: 0.5rem;
        }}
        .meta {{
            color: #666;
            font-size: 0.9rem;
        }}
        .body {{
            font-size: 1.1rem;
            line-height: 1.8;
            white-space: pre-wrap;
            margin-bottom: 2rem;
        }}
        .images {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
            gap: 1rem;
        }}
        .image {{
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
        }}
        .image img {{
            width: 100%;
            height: auto;
            display: block;
        }}
        .image-caption {{
            padding: 0.5rem;
            background: #f5f5f5;
            font-size: 0.85rem;
            text-align: center;
        }}
        .timestamp {{
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid #eee;
            color: #999;
            font-size: 0.85rem;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">{escape(title)}</h1>
        <div class="meta">
            Generated: {timestamp}
        </div>
    </div>
    <div class="body">{escape(body)}</div>
    <div class="images">
"""
    image_indices = []
    for idx, image_path in enumerate(image_paths):
        if os.path.exists(image_path):
            image_url = os.path.abspath(image_path)
            image_indices.append(idx)
            html_content += f"""
        <div class="image">
            <img src="{escape(image_url)}" alt="Generated image">
            <div class="image-caption">{escape(image_path)}</div>
        </div>
"""
        else:
            image_indices.append(None)

    html_content += """
    </div>
    <div class="timestamp">
        Generated by xianyu pipeline
    </div>
</body>
</html>
"""

    index_html = output_subdir / "index.html"
    with open(index_html, "w", encoding="utf-8") as f_out:
        f_out.write(html_content)

    metadata = {
        "title": title,
        "body": body,
        "image_paths": image_paths,
        "generated_at": timestamp,
        "html_path": str(index_html),
        "output_directory": str(output_subdir),
    }

    metadata_path = output_subdir / "metadata.json"
    with open(metadata_path, "w", encoding="utf-8") as f_out:
        json.dump(metadata, f_out, ensure_ascii=False, indent=2)

    return {
        "success": True,
        "output_path": str(index_html),
        "metadata_path": str(metadata_path),
        "metadata": metadata,
    }
