#!/usr/bin/env python3
"""
flywheel-scan.py — v0.7 knowledge flywheel pilot (REQUIREMENT for v0.7)

Reads all *.report.md in .ccc/reports/ + .ccc/verdicts/*, extracts failure
patterns + dedupes by content hash, writes candidate lesson to
.ccc/abnormal-reports/flywheel-candidate-<date>.md (NOT directly to docs/lessons.md).

Per Red Line 14 (Lesson 28): HUMAN REVIEW REQUIRED before any candidate
becomes a real lesson. This script ONLY writes to abnormal-reports/.
"""
from __future__ import annotations
import hashlib
import re
from pathlib import Path
from datetime import date

CCC = Path(__file__).resolve().parent.parent / ".ccc"
REPORTS = CCC / "reports"
VERDICTS = CCC / "verdicts"
ABNORMAL = CCC / "abnormal-reports"
ABNORMAL.mkdir(parents=True, exist_ok=True)

# Common failure markers — these are the patterns we want to surface
FAILURE_PATTERNS = [
    (r"(?i)\b(error|exception|failed|timeout|crashed|hanged)\b", "infrastructure_or_runtime"),
    (r"(?i)\b(circular\s+import|recursion\s+error)\b", "circular_import"),
    (r"(?i)\b(permission\s+denied|access\s+denied|forbidden)\b", "permission"),
    (r"(?i)\b(p0|critical|severity)\b", "severity_marker"),
    (r"(?i)\b(red\s*line\s*\d+)\b", "red_line_violation"),
    (r"(?i)\b(verifier|verification\s+failed)\b", "verification_gap"),
]


def content_hash(text: str) -> str:
    return hashlib.sha256(text.strip().encode()).hexdigest()[:12]


def scan() -> list[dict]:
    """Return list of {file, pattern_label, sentence, hash} dicts."""
    findings = []
    for src_dir in (REPORTS, VERDICTS):
        if not src_dir.exists():
            continue
        for f in src_dir.glob("*.md"):
            try:
                text = f.read_text()
            except Exception:
                continue
            for line in text.split("\n"):
                for pat, label in FAILURE_PATTERNS:
                    if re.search(pat, line):
                        snippet = line.strip()[:200]
                        if not snippet:
                            continue
                        findings.append({
                            "file": f.name,
                            "label": label,
                            "snippet": snippet,
                            "hash": content_hash(snippet + label),
                        })
    # Dedupe by hash
    seen = set()
    unique = []
    for f in findings:
        if f["hash"] in seen:
            continue
        seen.add(f["hash"])
        unique.append(f)
    return unique


def write_candidate(findings: list[dict]) -> Path:
    """Write candidate lesson file. NEVER directly modifies docs/lessons.md."""
    today = date.today().isoformat()
    out_path = ABNORMAL / f"flywheel-candidate-{today}.md"
    lines = [
        f"# Flywheel Candidate Lesson — {today}",
        "",
        "> ⚠️ This is a **candidate** — per [Red Line 14](../red-lines.md) it must be",
        "> human-reviewed before being merged into `docs/lessons.md`.",
        "",
        f"**Source files scanned**: {len({f['file'] for f in findings})}",
        f"**Unique findings**: {len(findings)}",
        f"**Generated by**: `scripts/flywheel-scan.py`",
        "",
        "## Findings",
        "",
    ]
    for f in findings:
        lines.append(f"### {f['label']} (in {f['file']})")
        lines.append(f"- **hash**: `{f['hash']}`")
        lines.append(f"- **snippet**: {f['snippet']}")
        lines.append("")
    out_path.write_text("\n".join(lines))
    return out_path


def main() -> int:
    findings = scan()
    if not findings:
        print("[flywheel] no findings — nothing to propose")
        return 0
    out = write_candidate(findings)
    print(f"[flywheel] wrote candidate: {out}")
    print(f"[flywheel] {len(findings)} unique findings (dedupe by sha256[:12])")
    print("[flywheel] NEXT: human reviews .ccc/abnormal-reports/" + out.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
